# Generated by Django 4.0.5 on 2022-10-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trending_tweet',
            name='tweet_time',
            field=models.DateTimeField(),
        ),
    ]
